language: go

env:
  - GO111MODULE=on

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - 1.16.x

before_install:
  - go get -v github.com/mattn/goveralls
  - go build

script:
  - goveralls -v -race -service=travis-ci

notifications:
  email:
    recipients:
      - info@miladrahimi.com
      - raskarpour@gmail.com
    on_success: change
    on_failure: always
