language: go

env:
  - GO111MODULE=on

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x

before_install:
  - go get -v github.com/mattn/goveralls

script:
  - go build
  - goveralls -v -race -service=travis-ci

notifications:
  email:
    recipients:
      - info@miladrahimi.com
    on_success: change
    on_failure: always
