name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:  
  test:
    strategy:
        fail-fast: false
        matrix:
          os:
            - ubuntu-latest
          go:
            - 1.17
            - 1.16
            - 1.15
            - 1.14
            - 1.13
            - 1.12
            - 1.11
            
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
    
    - name: Coveralls
      run: go get -v github.com/mattn/goveralls && go build && goveralls -v -race -service=github -repotoken=${{ COVERALLS_REPO_TOKEN }}
